name: Publish Release

on:
  push:
    tags:
      - "*.*"

jobs:
  release:
    name: Publish Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Publish Release
        uses: leomotors/release-action@v6
        with:
          mode: release
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          title: "MCV Quiz AI Solver"
